#: import REFS libs.REFS

<EntrypointScreenView>:
    id: EntrypointScreenView

    CStackLayout:
        size_hint: [1, 1]
        bg_color: app.transparent

        UI:
            id: manager_screens

            CScreen:
                name: "home"
                CTextInputLayoutCircular:
                    id: searchinput
                    radius: self.height/2
                    pos: self.pos[0], root.height - dp(256)
                    pos_hint: {"center_x": 0.5}
                    size_hint: None, None
                    width: dp(576)
                    bg_color_focus: app.layer_hover_01
                    line_color_focus: app.transparent

                    ActiveButton:
                        id: engine_icon
                        icon: "blank"
                        icon_source: app.se_source
                        font_size: dp(28)
                        pos_hint: {"center_y": 0.5}
                        pos: dp(4), self.pos[1]
                        on_press:
                            root.se_dropdown.visibility = self.focus

                    FixedTextInput:
                        id: search_input
                        -baseline_color: app.transparent
                        size_hint_x: None
                        width: root.width - engine_icon.width - trailing_btn.width - dp(40)
                        pos: engine_icon.width + dp(4), self.pos[1]
                        pos_hint: {"center_y": 0.5}
                        multiline: False
                        padding: [dp(4), dp(14)]
                        hint_text: "Search"
                        font_size: sp(14)
                        input_type: "url"
                        on_text_validate:
                            app.search(self.text)
                            self.text = ""

                    CTextInputTrailingIconButton:
                        id: trailing_btn
                        icon: "search"
                        role: "Medium"
                        pos_hint: {"center_y": 0.5}
                        pos: searchinput.width - self.width - dp(4), self.pos[1]
                        on_press:
                            app.search(search_input.text)
                            search_input.text = ""

            BrowserWebView:
                id: web_view
                name: "webview"

<SEDropdown>:
    orientatiion: "vertical"
    adaptive: [False, True]
    size_hint_x: None
    width: dp(288)
    spacing: dp(16)
    padding: [dp(16)]
    
    SEOption:
        source: "assets/google-logo64.png"
        title: "Google"

    SEOption:
        source: "assets/bing-logo64.png"
        title: "Bing"


<SEOption>:
    canvas.after:
        Color:
            rgba: app.interactive if self.selected else app.transparent
        Line:
            width: dp(1)
            cap: "square"
            points: [self.x + dp(1), self.y + dp(4), self.x + dp(1), self.top - dp(4)]

    adaptive: [False, True]
    padding: [dp(32), dp(8)]
    spacing: dp(16)
    selected: True if app.current_se == self.title.lower() else False
    bg_color: app.layer_02 if self.selected else app.transparent
    on_press:
        self.selected = not self.selected
        app.current_se = self.title.lower()

    CIcon:  
        bg_source: root.source
        size_hint: None, None
        size: sp(28), sp(28)
        pos_hint: {"center_y": 0.5}

    CLabel:
        text: root.title
        pos_hint: {"center_y": 0.5}


        # CTabHeaderCircular:
        #     tab_manager: manager_screens
        #     adaptive: [True, True]
        #     pos_hint: {"center_x": 0.5}
        #     pos: self.pos[0], dp(16)
        #     spacing: dp(8)
        #     padding: [dp(32), dp(4)]
        #     radius: self.height/2
        #     bg_color: app.background
        #     allow_no_selection: True

        #     UIShellButton:
        #         icon: "arrow--left"
        #         font_size: plex_14
        #         adaptive: [True, True]
        #         on_press:
        #             root.go_back()

        #     UIShellButton:
        #         icon: "arrow--right"
        #         font_size: plex_14
        #         adaptive: [True, True]
        #             app.current_webview.go_forward()

        #     CTabHeaderItem:
        #         icon: "home"
        #         icon_size: plex_18
        #         adaptive: [True, True]
        #         name_tab: "home"
        #         selected: True if manager_screens.current == "home" else False
        #         on_press:
        #             app.current_webview.go_home()

        #     UIShellButton:
        #         icon: "restart"
        #         font_size: plex_14
        #         adaptive: [True, True]
        #         on_press:
        #             app.current_webview.reload()

        #     CTabHeaderItem:
        #         icon: "settings"
        #         icon_size: plex_18
        #         adaptive: [True, True]
        #         name_tab: "settings"
        #         selected: True if manager_screens.current == "settings" else False
